Makes the pipeline faster by importing only a day at a time

diff --git a/scripts/publish_postgres_tracks b/scripts/publish_postgres_tracks
--- a/scripts/publish_postgres_tracks
+++ b/scripts/publish_postgres_tracks
@@ -5,7 +5,9 @@ source pipe-tools-utils
 THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
 ASSETS=${THIS_SCRIPT_DIR}/../assets
 ARGS=( \
+  DATE_RANGE \
   SOURCE \
+  TEMP_DATASET \
   TEMP_BUCKET \
   DEST_INSTANCE \
   DEST_CONNECTION_STRING \
@@ -34,26 +36,64 @@ for index in ${!ARGS[*]}; do
   declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
 done
 
+IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
+if [[ -z $END_DATE ]]; then
+  END_DATE=${START_DATE}
+fi
+################################################################################
+# Extracting the records we need to import to a different temp table
+################################################################################
+echo "Fetching only the records we need to export"
+UUID=$(uuidgen)
+TEMP_EXTRACT_TABLE="${TEMP_DATASET}.${UUID//-/_}"
+EXTRACT_SQL=${ASSETS}/bigquery/extract-tracks.sql.j2
+echo "  Running query to destionation table ${TEMP_EXTRACT_TABLE}"
+jinja2 ${EXTRACT_SQL} \
+  -D table=${SOURCE//:/.} \
+  -D start=${START_DATE} \
+  -D end=${END_DATE} \
+  | bq --headless query \
+  -n 0 \
+  --destination_table ${TEMP_EXTRACT_TABLE} \
+  --use_legacy_sql=false
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to fetch the records to export into ${TEMP_EXTRACT_TABLE}"
+  exit 1
+fi
+echo "  Extracted the records to export into ${TEMP_EXTRACT_TABLE}"
+
 ################################################################################
 # Export records to json files
 ################################################################################
-echo "Exporting records from $SOURCE"
-TEMP_PATH=gs://${TEMP_BUCKET}/pipe-vessels/$( date -u "+%FT%T.%N" )
-EXTRACT_PATH=$TEMP_PATH/bq/*.json
+echo "Exporting records from $TEMP_EXTRACT_TABLE"
+TEMP_PATH=gs://${TEMP_BUCKET}/pipe-vessels/publish-postgres-tracks/$( date -u "+%FT%T.%N" )
+EXTRACT_PATH=$TEMP_PATH/bq/*.json.gz
 bq --headless extract \
+  --compression=GZIP \
   --destination_format=NEWLINE_DELIMITED_JSON \
-  $SOURCE \
+  $TEMP_EXTRACT_TABLE \
   $EXTRACT_PATH
 if [ "$?" -ne 0 ]; then
-  echo "  Unable to extract ${SOURCE} to ${EXTRACT_PATH}"
+  echo "  Unable to extract ${TEMP_EXTRACT_TABLE} to ${EXTRACT_PATH}"
   exit 1
 fi
-echo "  Exported records from ${SOURCE} to ${EXTRACT_PATH}"
+echo "  Exported records from ${TEMP_EXTRACT_TABLE} to ${EXTRACT_PATH}"
+
+################################################################################
+# Delete the temp extract table
+################################################################################
+echo "Deleting temp extract table ${TEMP_EXTRACT_TABLE}"
+bq rm -t -f ${TEMP_EXTRACT_TABLE}
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to delete the temp extract table ${TEMP_EXTRACT_TABLE}"
+  exit 1
+fi
+echo "  Deleted the temp extract table ${TEMP_EXTRACT_TABLE}"
 
 ################################################################################
 # Download files locally
 ################################################################################
-echo "Downloading records from ${SOURCE} to local disk"
+echo "Downloading records from ${TEMP_EXTRACT_TABLE} to local disk"
 LOCAL_JSON_PATH=./data/json/
 mkdir -p ${LOCAL_JSON_PATH}
 gsutil -m cp ${EXTRACT_PATH} ${LOCAL_JSON_PATH}
@@ -76,7 +116,7 @@ if [ "$?" -ne 0 ]; then
   exit 1
 fi
 echo "Converting json records to csv format"
-cat ${LOCAL_JSON_PATH}/*.json | python -m pipe_vessels.postgres.tracks ${LOCAL_CSV_FILE}
+zcat ${LOCAL_JSON_PATH}/*.json.gz | python -m pipe_vessels.postgres.tracks ${LOCAL_CSV_FILE}
 if [ "$?" -ne 0 ]; then
   echo "  Unable to convert records from JSON to CSV format"
   exit 1
@@ -97,6 +137,8 @@ echo "Setting up database for data import"
 SETUP_SQL=${ASSETS}/postgres/tracks_setup.sql.j2
 jinja2 ${SETUP_SQL} \
   -D table_name=${DEST_TABLE} \
+  -D start=${START_DATE} \
+  -D end=${END_DATE} \
   | psql -v ON_ERROR_STOP=ON "${DEST_CONNECTION_STRING}"
 if [ "$?" -ne 0 ]; then
   echo "  Unable to set database up for data import"
diff --git a/scripts/publish_vessel_info b/scripts/publish_vessel_info
--- a/scripts/publish_vessel_info
+++ b/scripts/publish_vessel_info
@@ -6,7 +6,7 @@ THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
 ASSETS=${THIS_SCRIPT_DIR}/../assets
 ARGS=( \
   SOURCE_QUERY \
-  TEMP_EXTRACT_TABLE_PREFIX
+  TEMP_DATASET \
   TEMP_BUCKET \
   ELASTIC_SEARCH_SERVER_URL \
   ELASTIC_SEARCH_SERVER_AUTH \
@@ -18,7 +18,8 @@ ARGS=( \
 # Validate and extract arguments
 ################################################################################
 display_usage() {
-  echo -e "\nUsage:\n$ SOURCE_QUERY TEMP_EXTRACT_TABLE_PREFIX TEMP_BUCKET ELASTIC_SEARCH_SERVER_URL ELASTIC_SEARCH_SERVER_AUTH ELASTIC_SEARCH_INDEX_ALIAS ELASTIC_SEARCH_INDEX_MAPPINGS\n"
+  ARG_NAMES=$(echo "${ARGS[*]}")
+  echo -e "\nUsage:\n$0 $ARG_NAMES\n"
 }
 
 if [[ $# -ne ${#ARGS[@]} ]]
@@ -38,25 +39,28 @@ done
 # Running bigquery query to generate vessel information
 ################################################################################
 echo "Running vessel information query"
-CURRENT_TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
-TEMP_EXTRACT_TABLE="${TEMP_EXTRACT_TABLE_PREFIX}_${CURRENT_TIMESTAMP}"
-echo "${SOURCE_QUERY}" | bq --headless query \
+UUID=$(uuidgen)
+TEMP_EXTRACT_TABLE="${TEMP_DATASET}.${UUID//-/_}"
+echo "  Running query to destination table ${TEMP_EXTRACT_TABLE}"
+echo "${SOURCE_QUERY}" \
+  | bq --headless query \
+  -n 0 \
   --destination_table ${TEMP_EXTRACT_TABLE} \
-  --use_legacy_sql=false \
-  --replace
+  --use_legacy_sql=false
 if [ "$?" -ne 0 ]; then
   echo "  Unable to run vessel information query into ${TEMP_EXTRACT_TABLE}"
   exit 1
 fi
-echo "Extracted vessel information into ${TEMP_EXTRACT_TABLE}"
+echo "  Extracted vessel information into ${TEMP_EXTRACT_TABLE}"
 
 #################################################################################
 ## Export records to json files
 #################################################################################
 echo "Exporting records from $TEMP_EXTRACT_TABLE"
-TEMP_PATH=gs://${TEMP_BUCKET}/pipe-vessels/${CURRENT_TIMESTAMP}
-TEMP_EXTRACT_PATH=$TEMP_PATH/bq/*.json
+TEMP_PATH=gs://${TEMP_BUCKET}/pipe-vessels/publish-vessel-info/$( date -u "+%FT%T.%N" )
+TEMP_EXTRACT_PATH=$TEMP_PATH/bq/*.json.gz
 bq --headless extract \
+  --compression=GZIP \
   --destination_format=NEWLINE_DELIMITED_JSON \
   $TEMP_EXTRACT_TABLE \
   $TEMP_EXTRACT_PATH
@@ -64,7 +68,18 @@ if [ "$?" -ne 0 ]; then
   echo "  Unable to extract ${TEMP_EXTRACT_TABLE} to ${TEMP_EXTRACT_PATH}"
   exit 1
 fi
-echo "Exported records from ${TEMP_EXTRACT_TABLE} to ${TEMP_EXTRACT_PATH}"
+echo "  Exported records from ${TEMP_EXTRACT_TABLE} to ${TEMP_EXTRACT_PATH}"
+
+################################################################################
+# Delete the temp extract table
+################################################################################
+echo "Deleting temp extract table ${TEMP_EXTRACT_TABLE}"
+bq rm -t -f ${TEMP_EXTRACT_TABLE}
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to delete the temp extract table ${TEMP_EXTRACT_TABLE}"
+  exit 1
+fi
+echo "  Deleted the temp extract table ${TEMP_EXTRACT_TABLE}"
 
 ################################################################################
 # Download files locally
@@ -83,9 +98,10 @@ echo "  Downloaded records from ${TEMP_EXTRACT_PATH}"
 # Load data into Elastic Search
 ################################################################################
 echo "Loading data into Elastic Search"
-cat ${LOCAL_JSON_PATH}/*.json | python -u -m pipe_vessels.elasticsearch.importer $ELASTIC_SEARCH_SERVER_URL $ELASTIC_SEARCH_SERVER_AUTH $ELASTIC_SEARCH_INDEX_ALIAS "$ELASTIC_SEARCH_INDEX_MAPPINGS"
+zcat ${LOCAL_JSON_PATH}/*.json.gz \
+  | python -u -m pipe_vessels.elasticsearch.importer $ELASTIC_SEARCH_SERVER_URL $ELASTIC_SEARCH_SERVER_AUTH $ELASTIC_SEARCH_INDEX_ALIAS "$ELASTIC_SEARCH_INDEX_MAPPINGS"
 if [ "$?" -ne 0 ]; then
   echo "  Unable to load data into Elastic Search"
   exit 1
 fi
-echo "Loaded data into Elastic Search"
+echo "  Loaded data into Elastic Search"
